### ISSUE TITLE
Getting an Error in the Day 34 Part - 2

### ISSUE THREAD

**Issue by vikramadit** [vikramadit/Project7#2]
I am getting the following error in the appDelegate file of the project:
"Cannot find 'window' in scope"
I have used the same code as the tutor, This is the code:
`
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        if let tabBarController = window?.rootViewController as? UITabBarController {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let vc = storyboard.instantiateViewController(identifier: "NavController")
            vc.tabBarItem = UITabBarItem(tabBarSystemItem: .topRated, tag: 1)
            tabBarController.viewControllers?.append(vc)
            
        }
        
        return true
    }

`
How can I fix this?

**Comment by gsandroshvili** [comment]
var window: UIWindow?

use this inside AppDelegate class
